baseURL = 'https://blog.exemplars.io'
languageCode = 'en-us'
title = "Satya Tanwar - On Tech And Life"
theme = 'mainroad'
enableEmoji = true
#menu items

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  ## Cloud Menu
  #[[menu.main]]
  #  identifier = "cloud"
  #  name = "Cloud"
  #  url = "/post/cloud/"
  #  weight = 2
  
  ## Architecture Menu

  #[[menu.main]]
  #  identifier = "architecture"
  #  name = "Architecture"
  #  url = "/post/architecture"
  #  weight = 9
     
 ## Life Menu
  #[[menu.main]]
  #  identifier = "devops"
  #  name = "Devops"
  #  url = "/post/devops"
  #  weight = 10

  ## Life Menu
  #[[menu.main]]
  #  identifier = "social"
  #  name = "Social"
  #  url = "/post/social"
  #  weight = 10

  ## About Menu
  #[[menu.main]]
  #  identifier = "about"
  #  name = "About"
  #  url = "/about/"
  #  weight = 20


[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Satya Tanwar's Tech & Social Blog." # Site description. Used in meta description
  copyright = "satyatanwar.com" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  summaryLength = 10
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "cloud", "architecture", "social"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files


[Params.thumbnail]
  visibility = ["list"]

[Author] # Used in authorbox
  name = "Satya Tanwar"
  bio = "Satya Tanwar has 15+ years in Technology Development and core expertise in the area of application architecture, cloud computing and container based app development."
  avatar = "img/logo.png"



[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"


[Params.logo]
  image = "img/logo.png" # Logo image. Path relative to "static"
  title = "On Tech and Life" # Logo title, otherwise will use site title
  subtitle = "Satya Tanwar's Opinionated Blog" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right"  # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]
  #widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget



#[[Params.widgets.social.custom]]
# title = "Home Page"
#  url = "https://blog.satyatanwar.com"




